[package]
name = "enostr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ewebsock = { version = "0.2.0", features = ["tls"] }
serde_derive = "1"
serde = { version = "1", features = ["derive"] } # You only need this if you want app persistence
serde_json = "1.0.89"
nostr = { version = "0.30.0" }
#nostrdb = { git = "https://github.com/damus-io/nostrdb-rs", rev = "6d22af6d5159be4c9e4579f8c9d3af836e0d470a" }
nostrdb = { git = "https://github.com/kernelkind/nostrdb-rs" , rev = "a004ce0b6c62428a7a8f7fd50d12d6a0dd88861e"}
hex = "0.4.3"
tracing = "0.1.40"
env_logger = "0.11.1"
